### ISSUE TITLE
讨论。。。

### ISSUE THREAD

**Issue by Bian-Sh** [ancientElement/LockStep_Demo#1]
代码没看，但是看了 readme 有收获哦~
我看到几个小问题：
1. 示例代码中 idel和move状态没有正确翻转
![image](https://github.com/ancientElement/LockStep_Demo/assets/24520547/1d8fc50a-ae66-413f-8229-558434b22abc)
2. 示例代码中很多函数和注释都出现在了同一行。
3. 服务器收集用户逻辑中如果必须等到所有客户反馈有点太坑，如果有客户端延迟严重，那这个游戏没法进行下去了
4. 客户端中不应该是到了指定的时间才会上传用户操作，因为很多时候用户的操作极有可能发生在你监控之外，应该是你说的收集用户操作知道下一帧到来再报告给服务器。

以上只是个人管见，我也没有多少网络游戏的实战经验，就讨论讨论

**Comment by ancientElement** [comment]
感谢你能够这么认真观看我的代码,因为这只是一个小Demo,开发的时间不长。
并且我也是初次接触帧同步,还没有运用到我的项目中。
所以感谢你能够指出这些问题,我在之后继续制作帧同步部分的时候会解决这些问题。
关于第二点应该是复制的时候格式造成的问题，我会去修改一下。
再次感谢你，这是第一次别人在我的GITHUB上提出ISSUES
